### ISSUE TITLE
Warnings as errors not working on Ubuntu 22.04

### ISSUE THREAD

**Issue by nbolton** [deskflow/deskflow#7739]
### Project

Deskflow

### Deskflow version number

1.17.0.76

### Build type

CI

### OS versions/distros

- Ubuntu 22.04
- FreeBSD

### What steps will reproduce the problem?

1. Apply patch below
2. Run CI

Expect: All targets should fail because there is a compiler warning
Actual: All fail except Ubuntu 22.04 and FreeBSD

![image](https://github.com/user-attachments/assets/6e8ff272-fa1a-42c5-a98d-1f0562a41005)

### Log output

```shell
Ubuntu 22.04:

/__w/deskflow/deskflow/src/cmd/deskflows/deskflows.cpp: In function 'int main(int, char**)':
/__w/deskflow/deskflow/src/cmd/deskflows/deskflows.cpp:53:21: warning: 'void deprecatedFunction()' is deprecated: test [-Wdeprecated-declarations]
   53 |   deprecatedFunction();
      |   ~~~~~~~~~~~~~~~~~~^~
/__w/deskflow/deskflow/src/cmd/deskflows/deskflows.cpp:40:6: note: declared here
   40 | void deprecatedFunction()
      |      ^~~~~~~~~~~~~~~~~~
[ 81%] Building CXX object 
```

FreeBSD:
```shell
  /home/runner/work/deskflow/deskflow/src/cmd/deskflows/deskflows.cpp:53:3: error: 'deprecatedFunction' is deprecated: test [-Werror,-Wdeprecated-declarations]
     53 |   deprecatedFunction();
        |   ^
  /home/runner/work/deskflow/deskflow/src/cmd/deskflows/deskflows.cpp:39:3: note: 'deprecatedFunction' has been explicitly marked deprecated here
     39 | [[deprecated("test")]]
        |   ^
  1 error generated[ 85%] Building CXX object src/test/unittests/CMakeFiles/unittests.dir/deskflow/IKeyStateTests.cpp.o
  .
  gmake[2]: *** [src/cmd/deskflows/CMakeFiles/deskflow-server.dir/build.make:76: src/cmd/deskflows/CMakeFiles/deskflow-server.dir/deskflows.cpp.o] Error 1
  gmake[1]: *** [CMakeFiles/Makefile2:848: src/cmd/deskflows/CMakeFiles/deskflow-server.dir/all] Error 2
  gmake[1]: *** Waiting for unfinished jobs....
```

### Additional information

Perhaps low priority since at least warnings as errors is working on most Linux runners.

Test warning:
```diff
diff --git a/src/cmd/deskflows/deskflows.cpp b/src/cmd/deskflows/deskflows.cpp
index 85f6af24..6ed3eb4a 100644
--- a/src/cmd/deskflows/deskflows.cpp
+++ b/src/cmd/deskflows/deskflows.cpp
@@ -19,6 +19,7 @@
 #include "arch/Arch.h"
 #include "base/EventQueue.h"
 #include "base/Log.h"
+#include "common/basic_types.h"
 #include "deskflow/ServerApp.h"
 
 #if SYSAPI_WIN32
@@ -35,6 +36,12 @@
 #error Platform not supported.
 #endif
 
+[[deprecated("test")]]
+void deprecatedFunction()
+{
+  // Do nothing
+}
+
 int main(int argc, char **argv)
 {
 #if SYSAPI_WIN32
@@ -42,6 +49,9 @@ int main(int argc, char **argv)
   ArchMiscWindows::setInstanceWin32(GetModuleHandle(NULL));
 #endif
 
+  // TODO: remove test warning as errors.
+  deprecatedFunction();
+
   Arch arch;
   arch.init();

```

It seems that Ubuntu 22.04 does note that the option won't be used:
```
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_COMPILE_WARNING_AS_ERROR
```
... I couldn't see this on FreeBSD though.

**Comment by sithlord48** [comment]
`New in version 3.24.`
we need cmake 3.24 for it to work on that platform. let me split my cmake pr

**Comment by sithlord48** [comment]
Fixed by #7743
